# docker-compose.yml
version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    # environment:
    #   DATABASE_URL: postgres://user:pass@postgres:5432/db
    #   NODE_ENV: development
    #   PORT: 3000
    ports:
      - '3000:3000'
    command: yarn dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:12-alpine
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      #- ./docker/postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
